[package]
name = "blockchain"
version = "0.1.0"
authors = ["tensor-programming <abeltensor@tensor-programming.com>"]

[dependencies]
time = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha2 = "*" 